version: "3.9"
services:
  dev:
    build:
      context: .
    ports:
      - "5900:5900"
    shm_size: '2gb'
    deploy:

      resources:
        limits:
          cpus: "8"
          memory: 4G
        reservations:
          cpus: "8"
          memory: 4G
