version: "2.4"

services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "5900:5900"
    shm_size: '2gb'
    # command: Xtigervnc :0 -geometry 1920x1080 -SecurityTypes None
    tty: true
    environment:
      - DISPLAY=:0
      - SCALE=1
    cpuset: 0-7
    mem_limit: 4g
    volumes:
      - ./shared:/shared